# Generated by Django 5.0.6 on 2024-05-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=40)),
                ('Number', models.IntegerField()),
                ('Date', models.DateField()),
                ('Person', models.IntegerField(max_length=2)),
            ],
        ),
    ]
