# Generated by Django 5.0.6 on 2024-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='Number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='Person',
            field=models.IntegerField(max_length=5),
        ),
    ]
